import { SessionProvider } from "next-auth/react";
import "./globals.css";
import { Raleway } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";

const raleway = Raleway({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Advanced POS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.className}`}>
        <Toaster />
        <SessionProvider>
        {children}
        </SessionProvider>
        </body>
    </html>
  );
}
